---
# ci_down.yml
# Destroy the CI instance and associated resources
- name: Destroy all CI resources
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - gce_vars/auth
    - gce_vars/ci_machine

  tasks:
    - name: Delete the DNS A record
      command: common_files/setdns delete -n {{ machine_names }}-{{ project_id }} -d {{ project_domain }} -p {{ project_id }} -c {{ credentials_file }}
      args:
        removes: "/tmp/{{ machine_names }}-{{ project_id }}.dns"

    - name: Destroy the CE instance
      gce:
        instance_names: "{{ machine_names }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: absent

    - name: Destroy the http firewall rule
      gce_net:
        fwname: all-http
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: absent

    - name: Destroy the https firewall rule
      gce_net:
        fwname: all-https
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: absent

    - name: Make sure the persistent disks are destroyed
      gce_pd: name={{ item.name }} zone={{ item.zone }} state=absent
              project_id={{ project_id }} credentials_file={{ credentials_file }} service_account_email={{ service_account_email }}
      with_items:
        - { name: "jenkins", zone: "us-central1-a" }
