---
# compute-video-demo-ansible
- name: Create Compute Engine instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - gce_vars/auth
    - gce_vars/ci_machine

  roles:
    - gce-instances
    - gce-network

- name: Deploy Jenkins server using Docker
  hosts: gce_instances
  connection: ssh
  gather_facts: false
  become: true

  vars_files:
    - gce_vars/auth
    - gce_vars/ci_machine

  vars:
    jenkins_version: "2.32.3"
    jenkins_hostname: "{{ machine_names }}-{{ project_id }}"
    jenkins_url: "https://{{ jenkins_hostname }}.{{ project_domain }}"
    jenkins_port: 443
    jenkins_ssl_cert: ssl/fullchain.pem
    jenkins_ssl_key: ssl/privkey-rsa.pem
    jenkins_install_via: "docker"
    jenkins_jobs: [
        "from-git-repository"
      ]
    jenkins_plugins:
      - git
      - log-parser
      - copyartifact
      - workflow-aggregator
      - workflow-multibranch
      - docker-workflow
      - template-project
      - google-login

  tasks:
    - name: Install setdns script on GCE host
      template:
        src: common_files/setdns
        dest: /usr/local/bin/setdns
        owner: root
        group: root
        mode: '0755'

  roles:
    - deploy-docker
    - get-ssl
    - ansible-jenkins

