---
# file: roles/deploy-docker/tasks/main.yml
- name: Install Docker
  apt: 
    name: docker.io

- name: Start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Configure Jenkins container to restart automatically
  template:
    src: docker-jenkins.service
    dest: /etc/systemd/system/docker-jenkins.service
    owner: root
    group: root
    mode: '0644'

- name: Restart Jenkins container in Docker engine upon reboot
  systemd:
    name: docker-jenkins
    enabled: yes

- name: Install Python pip
  apt:
    name: python-pip

- name: Install Docker Python module
  pip:
    name: docker-py

- name: Install Google Cloud Python module
  pip:
    name: google-cloud

- name: Add main login user, {{ ansible_ssh_user }}, to 'docker' group
  user: name='{{ ansible_ssh_user }}'
        groups=docker
        append=yes
